"""Generate Python and TypeScript definitions from the schema YAML.

The schema is authoritative. Anything this script writes is disposable and must
never be edited by hand — CI regenerates and fails on a diff.

This lives outside the `pitwall_schema` package on purpose: that package
re-exports the generated module, so a generator importing it could never run on
a fresh checkout before the first generation.
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_DIR = ROOT / "schema"
PY_OUT = ROOT / "src" / "pitwall_schema" / "_generated.py"
TS_OUT = ROOT / "generated" / "schema.ts"

BANNER = "Generated by packages/schema codegen. Do not edit; edit schema/*.yaml."


@dataclass(frozen=True)
class Channel:
    key: str
    display_en: str
    display_ru: str
    unit: str | None
    display_unit: str | None
    group: str
    dtype: str
    rate_hz: int
    derived: bool
    doc: str | None


def _label(value: Any, lang: str) -> str:
    """Axis and group labels are either a plain string or an {en, ru} mapping."""
    if isinstance(value, dict):
        return str(value[lang])
    return str(value)


def expand_channels(spec: dict[str, Any]) -> list[Channel]:
    axes = spec["axes"]
    out: list[Channel] = []

    for raw in spec["channels"]:
        axis_names = raw.get("expand", [])
        combos: list[dict[str, dict[str, Any]]] = [{}]
        for axis in axis_names:
            combos = [{**combo, axis: value} for combo in combos for value in axes[axis]]

        for combo in combos:
            key = raw["key"]
            display_en = _label(raw["display"], "en")
            display_ru = _label(raw["display"], "ru")
            for axis, value in combo.items():
                token = f"{{{axis}}}"
                key = key.replace(token, str(value["id"]))
                display_en = display_en.replace(token, _label(value["label"], "en"))
                display_ru = display_ru.replace(token, _label(value["label"], "ru"))

            doc = raw.get("doc")
            out.append(
                Channel(
                    key=key,
                    display_en=display_en,
                    display_ru=display_ru,
                    unit=raw.get("unit"),
                    display_unit=raw.get("display_unit"),
                    group=raw["group"],
                    dtype=raw["dtype"],
                    rate_hz=int(raw["rate_hz"]),
                    derived=bool(raw.get("derived", False)),
                    doc=doc.strip() if doc else None,
                )
            )

    seen: set[str] = set()
    for channel in out:
        if channel.key in seen:
            raise ValueError(f"duplicate channel key after expansion: {channel.key}")
        seen.add(channel.key)

    return out


def _py_literal(value: str | None) -> str:
    return "None" if value is None else repr(value)


def render_python(channels: list[Channel], protocol: dict[str, Any]) -> str:
    lines = [
        f'"""{BANNER}"""',
        "",
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass",
        "from typing import Final, Literal",
        "",
        "",
        "@dataclass(frozen=True, slots=True)",
        "class Channel:",
        "    key: str",
        "    display_en: str",
        "    display_ru: str",
        "    unit: str | None",
        "    display_unit: str | None",
        "    group: str",
        "    dtype: str",
        "    rate_hz: int",
        "    derived: bool",
        "    doc: str | None",
        "",
        "",
        f"PROTOCOL_VERSION: Final[int] = {protocol['version']}",
        "",
    ]

    keys = ", ".join(repr(c.key) for c in channels)
    lines += [f"ChannelKey = Literal[{keys}]", "", "CHANNELS: Final[dict[str, Channel]] = {"]
    for c in channels:
        lines.append(
            f"    {c.key!r}: Channel({c.key!r}, {c.display_en!r}, {c.display_ru!r}, "
            f"{_py_literal(c.unit)}, {_py_literal(c.display_unit)}, {c.group!r}, "
            f"{c.dtype!r}, {c.rate_hz}, {c.derived!r}, {_py_literal(c.doc)}),"
        )
    lines += ["}", ""]

    roles = ", ".join(repr(r["id"]) for r in protocol["roles"])
    frames = ", ".join(repr(f["id"]) for f in protocol["frames"])
    lines += [
        f"Role = Literal[{roles}]",
        f"FrameId = Literal[{frames}]",
        "",
        f"ROLES: Final[tuple[str, ...]] = ({roles},)",
        f"FRAME_IDS: Final[tuple[str, ...]] = ({frames},)",
        "",
    ]
    return "\n".join(lines)


def _ts_literal(value: str | None) -> str:
    if value is None:
        return "null"
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def render_typescript(channels: list[Channel], protocol: dict[str, Any]) -> str:
    lines = [
        f"// {BANNER}",
        "",
        "export interface Channel {",
        "  key: ChannelKey;",
        "  displayEn: string;",
        "  displayRu: string;",
        "  unit: string | null;",
        "  displayUnit: string | null;",
        "  group: string;",
        "  dtype: string;",
        "  rateHz: number;",
        "  derived: boolean;",
        "  doc: string | null;",
        "}",
        "",
        f"export const PROTOCOL_VERSION = {protocol['version']} as const;",
        "",
        "export type ChannelKey =",
    ]
    lines += [f"  | {_ts_literal(c.key)}" for c in channels]
    lines[-1] += ";"
    lines += ["", "export const CHANNELS: Record<ChannelKey, Channel> = {"]
    for c in channels:
        key = _ts_literal(c.key)
        lines.append(
            f"  {key}: {{ key: {key}, displayEn: {_ts_literal(c.display_en)}, "
            f"displayRu: {_ts_literal(c.display_ru)}, unit: {_ts_literal(c.unit)}, "
            f"displayUnit: {_ts_literal(c.display_unit)}, group: {_ts_literal(c.group)}, "
            f"dtype: {_ts_literal(c.dtype)}, rateHz: {c.rate_hz}, "
            f"derived: {'true' if c.derived else 'false'}, doc: {_ts_literal(c.doc)} }},"
        )
    lines += ["};", ""]

    roles = " | ".join(_ts_literal(r["id"]) for r in protocol["roles"])
    frames = " | ".join(_ts_literal(f["id"]) for f in protocol["frames"])
    lines += [
        f"export type Role = {roles};",
        f"export type FrameId = {frames};",
        "",
    ]
    return "\n".join(lines)


def build() -> dict[Path, str]:
    channels_spec = yaml.safe_load((SCHEMA_DIR / "channels.yaml").read_text(encoding="utf-8"))
    protocol_spec = yaml.safe_load((SCHEMA_DIR / "protocol.yaml").read_text(encoding="utf-8"))
    channels = expand_channels(channels_spec)

    known_groups = {g["id"] for g in channels_spec["groups"]}
    for channel in channels:
        if channel.group not in known_groups:
            raise ValueError(f"channel {channel.key} references unknown group {channel.group}")

    return {
        PY_OUT: render_python(channels, protocol_spec),
        TS_OUT: render_typescript(channels, protocol_spec),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if generated files are stale instead of writing them.",
    )
    args = parser.parse_args()

    stale: list[Path] = []
    for path, content in build().items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        if args.check:
            stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT.parent.parent)}")

    if stale:
        for path in stale:
            print(f"stale: {path}", file=sys.stderr)
        print("run `uv run pitwall-codegen` and commit the result", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
