"""Generated by packages/schema codegen. Do not edit; edit schema/*.yaml."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Final, Literal


@dataclass(frozen=True, slots=True)
class Channel:
    key: str
    display_en: str
    display_ru: str
    unit: str | None
    display_unit: str | None
    group: str
    dtype: str
    rate_hz: int
    derived: bool
    doc: str | None


PROTOCOL_VERSION: Final[int] = 1

ChannelKey = Literal['time', 'distance', 'lap', 'lap_time', 'speed', 'rpm', 'gear', 'throttle', 'brake', 'clutch', 'steering', 'pos_x', 'pos_y', 'pos_z', 'yaw', 'pitch', 'roll', 'accel_lat', 'accel_long', 'accel_vert', 'fuel_level', 'fuel_used_lap', 'tyre_temp_fl_i', 'tyre_temp_fl_m', 'tyre_temp_fl_o', 'tyre_temp_fr_i', 'tyre_temp_fr_m', 'tyre_temp_fr_o', 'tyre_temp_rl_i', 'tyre_temp_rl_m', 'tyre_temp_rl_o', 'tyre_temp_rr_i', 'tyre_temp_rr_m', 'tyre_temp_rr_o', 'tyre_press_fl', 'tyre_press_fr', 'tyre_press_rl', 'tyre_press_rr', 'tyre_wear_fl', 'tyre_wear_fr', 'tyre_wear_rl', 'tyre_wear_rr', 'brake_temp_fl', 'brake_temp_fr', 'brake_temp_rl', 'brake_temp_rr', 'brake_pressure_fl', 'brake_pressure_fr', 'brake_pressure_rl', 'brake_pressure_rr', 'susp_travel_fl', 'susp_travel_fr', 'susp_travel_rl', 'susp_travel_rr', 'ride_height_fl', 'ride_height_fr', 'ride_height_rl', 'ride_height_rr', 'water_temp', 'oil_temp', 'drs', 'ers_deploy', 'ers_store', 'abs_active', 'tc_active', 'damage_front', 'damage_rear', 'damage_left', 'damage_right', 'damage_engine', 'damage_gearbox', 'air_temp', 'track_temp', 'rain_pct', 'wind_speed', 'wind_dir']

CHANNELS: Final[dict[str, Channel]] = {
    'time': Channel('time', 'Time', 'Время', 's', None, 'session', 'f64', 100, False, 'Seconds since session start. Monotonic, the master time base.'),
    'distance': Channel('distance', 'Distance', 'Дистанция', 'm', None, 'session', 'f64', 100, False, "Distance travelled along the lap, measured from the start/finish line. This is the X axis for lap comparison, so it must come from the game's own lap distance where available rather than integrated speed."),
    'lap': Channel('lap', 'Lap', 'Круг', None, None, 'session', 'i32', 100, False, 'Current lap number, 1-based.'),
    'lap_time': Channel('lap_time', 'Lap Time', 'Время круга', 's', None, 'session', 'f64', 100, False, 'Elapsed time within the current lap.'),
    'speed': Channel('speed', 'Speed', 'Скорость', 'm/s', 'km/h', 'vehicle', 'f32', 100, False, None),
    'rpm': Channel('rpm', 'RPM', 'Обороты', 'rpm', None, 'vehicle', 'f32', 100, False, None),
    'gear': Channel('gear', 'Gear', 'Передача', None, None, 'vehicle', 'i32', 100, False, '-1 reverse, 0 neutral, 1..n forward.'),
    'throttle': Channel('throttle', 'Throttle', 'Газ', 'ratio', '%', 'inputs', 'f32', 100, False, None),
    'brake': Channel('brake', 'Brake', 'Тормоз', 'ratio', '%', 'inputs', 'f32', 100, False, None),
    'clutch': Channel('clutch', 'Clutch', 'Сцепление', 'ratio', '%', 'inputs', 'f32', 100, False, None),
    'steering': Channel('steering', 'Steering', 'Руль', 'ratio', None, 'inputs', 'f32', 100, False, 'Normalised, -1 full left to +1 full right.'),
    'pos_x': Channel('pos_x', 'Pos X', 'Позиция X', 'm', None, 'motion', 'f32', 100, False, None),
    'pos_y': Channel('pos_y', 'Pos Y', 'Позиция Y', 'm', None, 'motion', 'f32', 100, False, None),
    'pos_z': Channel('pos_z', 'Pos Z', 'Позиция Z', 'm', None, 'motion', 'f32', 100, False, "World coordinates. The track map is built from pos_x/pos_z in rF2's convention where Y is vertical — providers normalise so that the map plane is always x/y."),
    'yaw': Channel('yaw', 'Yaw', 'Рыскание', 'rad', 'deg', 'motion', 'f32', 100, False, None),
    'pitch': Channel('pitch', 'Pitch', 'Тангаж', 'rad', 'deg', 'motion', 'f32', 100, False, None),
    'roll': Channel('roll', 'Roll', 'Крен', 'rad', 'deg', 'motion', 'f32', 100, False, None),
    'accel_lat': Channel('accel_lat', 'G Lat', 'G поперечное', 'm/s2', 'g', 'motion', 'f32', 100, False, None),
    'accel_long': Channel('accel_long', 'G Long', 'G продольное', 'm/s2', 'g', 'motion', 'f32', 100, False, None),
    'accel_vert': Channel('accel_vert', 'G Vert', 'G вертикальное', 'm/s2', 'g', 'motion', 'f32', 100, False, None),
    'fuel_level': Channel('fuel_level', 'Fuel Level', 'Топливо', 'L', None, 'fuel', 'f32', 10, False, None),
    'fuel_used_lap': Channel('fuel_used_lap', 'Fuel Used (Lap)', 'Расход за круг', 'L', None, 'fuel', 'f32', 10, True, 'Derived, not read from the game: fuel level at lap start minus current. Only valid once a full lap has been observed.'),
    'tyre_temp_fl_i': Channel('tyre_temp_fl_i', 'Tyre Temp FL Inner', 'Темп. шины FL внутр.', 'K', 'degC', 'tyres', 'f32', 20, False, None),
    'tyre_temp_fl_m': Channel('tyre_temp_fl_m', 'Tyre Temp FL Middle', 'Темп. шины FL сред.', 'K', 'degC', 'tyres', 'f32', 20, False, None),
    'tyre_temp_fl_o': Channel('tyre_temp_fl_o', 'Tyre Temp FL Outer', 'Темп. шины FL внеш.', 'K', 'degC', 'tyres', 'f32', 20, False, None),
    'tyre_temp_fr_i': Channel('tyre_temp_fr_i', 'Tyre Temp FR Inner', 'Темп. шины FR внутр.', 'K', 'degC', 'tyres', 'f32', 20, False, None),
    'tyre_temp_fr_m': Channel('tyre_temp_fr_m', 'Tyre Temp FR Middle', 'Темп. шины FR сред.', 'K', 'degC', 'tyres', 'f32', 20, False, None),
    'tyre_temp_fr_o': Channel('tyre_temp_fr_o', 'Tyre Temp FR Outer', 'Темп. шины FR внеш.', 'K', 'degC', 'tyres', 'f32', 20, False, None),
    'tyre_temp_rl_i': Channel('tyre_temp_rl_i', 'Tyre Temp RL Inner', 'Темп. шины RL внутр.', 'K', 'degC', 'tyres', 'f32', 20, False, None),
    'tyre_temp_rl_m': Channel('tyre_temp_rl_m', 'Tyre Temp RL Middle', 'Темп. шины RL сред.', 'K', 'degC', 'tyres', 'f32', 20, False, None),
    'tyre_temp_rl_o': Channel('tyre_temp_rl_o', 'Tyre Temp RL Outer', 'Темп. шины RL внеш.', 'K', 'degC', 'tyres', 'f32', 20, False, None),
    'tyre_temp_rr_i': Channel('tyre_temp_rr_i', 'Tyre Temp RR Inner', 'Темп. шины RR внутр.', 'K', 'degC', 'tyres', 'f32', 20, False, None),
    'tyre_temp_rr_m': Channel('tyre_temp_rr_m', 'Tyre Temp RR Middle', 'Темп. шины RR сред.', 'K', 'degC', 'tyres', 'f32', 20, False, None),
    'tyre_temp_rr_o': Channel('tyre_temp_rr_o', 'Tyre Temp RR Outer', 'Темп. шины RR внеш.', 'K', 'degC', 'tyres', 'f32', 20, False, None),
    'tyre_press_fl': Channel('tyre_press_fl', 'Tyre Press FL', 'Давление FL', 'kPa', 'bar', 'tyres', 'f32', 20, False, None),
    'tyre_press_fr': Channel('tyre_press_fr', 'Tyre Press FR', 'Давление FR', 'kPa', 'bar', 'tyres', 'f32', 20, False, None),
    'tyre_press_rl': Channel('tyre_press_rl', 'Tyre Press RL', 'Давление RL', 'kPa', 'bar', 'tyres', 'f32', 20, False, None),
    'tyre_press_rr': Channel('tyre_press_rr', 'Tyre Press RR', 'Давление RR', 'kPa', 'bar', 'tyres', 'f32', 20, False, None),
    'tyre_wear_fl': Channel('tyre_wear_fl', 'Tyre Wear FL', 'Износ FL', 'ratio', '%', 'tyres', 'f32', 5, False, '0 is new, 1 is fully worn. Providers invert games that report the opposite.'),
    'tyre_wear_fr': Channel('tyre_wear_fr', 'Tyre Wear FR', 'Износ FR', 'ratio', '%', 'tyres', 'f32', 5, False, '0 is new, 1 is fully worn. Providers invert games that report the opposite.'),
    'tyre_wear_rl': Channel('tyre_wear_rl', 'Tyre Wear RL', 'Износ RL', 'ratio', '%', 'tyres', 'f32', 5, False, '0 is new, 1 is fully worn. Providers invert games that report the opposite.'),
    'tyre_wear_rr': Channel('tyre_wear_rr', 'Tyre Wear RR', 'Износ RR', 'ratio', '%', 'tyres', 'f32', 5, False, '0 is new, 1 is fully worn. Providers invert games that report the opposite.'),
    'brake_temp_fl': Channel('brake_temp_fl', 'Brake Temp FL', 'Темп. тормоза FL', 'K', 'degC', 'brakes', 'f32', 20, False, None),
    'brake_temp_fr': Channel('brake_temp_fr', 'Brake Temp FR', 'Темп. тормоза FR', 'K', 'degC', 'brakes', 'f32', 20, False, None),
    'brake_temp_rl': Channel('brake_temp_rl', 'Brake Temp RL', 'Темп. тормоза RL', 'K', 'degC', 'brakes', 'f32', 20, False, None),
    'brake_temp_rr': Channel('brake_temp_rr', 'Brake Temp RR', 'Темп. тормоза RR', 'K', 'degC', 'brakes', 'f32', 20, False, None),
    'brake_pressure_fl': Channel('brake_pressure_fl', 'Brake Press FL', 'Давление тормоза FL', 'bar', None, 'brakes', 'f32', 100, False, None),
    'brake_pressure_fr': Channel('brake_pressure_fr', 'Brake Press FR', 'Давление тормоза FR', 'bar', None, 'brakes', 'f32', 100, False, None),
    'brake_pressure_rl': Channel('brake_pressure_rl', 'Brake Press RL', 'Давление тормоза RL', 'bar', None, 'brakes', 'f32', 100, False, None),
    'brake_pressure_rr': Channel('brake_pressure_rr', 'Brake Press RR', 'Давление тормоза RR', 'bar', None, 'brakes', 'f32', 100, False, None),
    'susp_travel_fl': Channel('susp_travel_fl', 'Susp Travel FL', 'Ход подвески FL', 'm', 'mm', 'suspension', 'f32', 100, False, None),
    'susp_travel_fr': Channel('susp_travel_fr', 'Susp Travel FR', 'Ход подвески FR', 'm', 'mm', 'suspension', 'f32', 100, False, None),
    'susp_travel_rl': Channel('susp_travel_rl', 'Susp Travel RL', 'Ход подвески RL', 'm', 'mm', 'suspension', 'f32', 100, False, None),
    'susp_travel_rr': Channel('susp_travel_rr', 'Susp Travel RR', 'Ход подвески RR', 'm', 'mm', 'suspension', 'f32', 100, False, None),
    'ride_height_fl': Channel('ride_height_fl', 'Ride Height FL', 'Клиренс FL', 'm', 'mm', 'suspension', 'f32', 100, False, None),
    'ride_height_fr': Channel('ride_height_fr', 'Ride Height FR', 'Клиренс FR', 'm', 'mm', 'suspension', 'f32', 100, False, None),
    'ride_height_rl': Channel('ride_height_rl', 'Ride Height RL', 'Клиренс RL', 'm', 'mm', 'suspension', 'f32', 100, False, None),
    'ride_height_rr': Channel('ride_height_rr', 'Ride Height RR', 'Клиренс RR', 'm', 'mm', 'suspension', 'f32', 100, False, None),
    'water_temp': Channel('water_temp', 'Water Temp', 'Темп. воды', 'K', 'degC', 'engine', 'f32', 5, False, None),
    'oil_temp': Channel('oil_temp', 'Oil Temp', 'Темп. масла', 'K', 'degC', 'engine', 'f32', 5, False, None),
    'drs': Channel('drs', 'DRS', 'DRS', None, None, 'electronics', 'u8', 20, False, '0 unavailable, 1 available, 2 open. Null on cars without DRS.'),
    'ers_deploy': Channel('ers_deploy', 'ERS Deploy', 'ERS отдача', 'J', None, 'electronics', 'f32', 20, False, None),
    'ers_store': Channel('ers_store', 'ERS Store', 'ERS запас', 'J', None, 'electronics', 'f32', 20, False, None),
    'abs_active': Channel('abs_active', 'ABS Active', 'ABS активна', None, None, 'electronics', 'bool', 100, False, None),
    'tc_active': Channel('tc_active', 'TC Active', 'TC активна', None, None, 'electronics', 'bool', 100, False, None),
    'damage_front': Channel('damage_front', 'Damage Front', 'Повреждение перед', 'ratio', '%', 'damage', 'f32', 2, False, None),
    'damage_rear': Channel('damage_rear', 'Damage Rear', 'Повреждение зад', 'ratio', '%', 'damage', 'f32', 2, False, None),
    'damage_left': Channel('damage_left', 'Damage Left', 'Повреждение лево', 'ratio', '%', 'damage', 'f32', 2, False, None),
    'damage_right': Channel('damage_right', 'Damage Right', 'Повреждение право', 'ratio', '%', 'damage', 'f32', 2, False, None),
    'damage_engine': Channel('damage_engine', 'Damage Engine', 'Повреждение двигателя', 'ratio', '%', 'damage', 'f32', 2, False, None),
    'damage_gearbox': Channel('damage_gearbox', 'Damage Gearbox', 'Повреждение КПП', 'ratio', '%', 'damage', 'f32', 2, False, None),
    'air_temp': Channel('air_temp', 'Air Temp', 'Темп. воздуха', 'K', 'degC', 'weather', 'f32', 1, False, None),
    'track_temp': Channel('track_temp', 'Track Temp', 'Темп. трассы', 'K', 'degC', 'weather', 'f32', 1, False, None),
    'rain_pct': Channel('rain_pct', 'Rain', 'Дождь', 'ratio', '%', 'weather', 'f32', 1, False, None),
    'wind_speed': Channel('wind_speed', 'Wind Speed', 'Скорость ветра', 'm/s', None, 'weather', 'f32', 1, False, None),
    'wind_dir': Channel('wind_dir', 'Wind Direction', 'Направление ветра', 'rad', 'deg', 'weather', 'f32', 1, False, None),
}

Role = Literal['driver', 'engineer']
FrameId = Literal['hello', 'welcome', 'samples', 'scoring', 'session_state', 'agent_status', 'error']

ROLES: Final[tuple[str, ...]] = ('driver', 'engineer',)
FRAME_IDS: Final[tuple[str, ...]] = ('hello', 'welcome', 'samples', 'scoring', 'session_state', 'agent_status', 'error',)
