"""Frozen entry point.

PyInstaller needs a real script; the console-script shims generated by pip do
not survive freezing.
"""

from __future__ import annotations

import multiprocessing
import sys

from pitwall_agent.cli import main

if __name__ == "__main__":
    # Without this a frozen build re-executes the whole program in any worker
    # process, which shows up as the app starting itself several times.
    multiprocessing.freeze_support()
    sys.exit(main())
